---
title: "Project2019"
author: "Mirko Michovich"
date: "5/7/2019"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#install.packages("maps")
#install.packages("mapdata")
#install.packages("ggmap")
#install.packages("mapproj")
#install.packages("ggplot2")

library(maps)
library(mapdata)
library(ggmap) #use to read map
library(mapproj) #map tools kits
library(ggplot2) #read the map data
library(tidyverse)
library(stringr)

register_google(key = "AIzaSyARb0Fsx8OYgRVToJK_2Abl4r1lO_1ACCY", write = TRUE)

```

```{r}
# Define UI for miles per gallon application
shinyUI(pageWithSidebar(

  # Application title
  headerPanel("Miles Per Gallon"),

  sidebarPanel(),

  mainPanel()
))

```


```{r}
collisions_subset_10000 <- read.csv("Collision 10000.csv")
#collisions_subset_10000 <- collisions[sample(nrow(collisions),10000),]

extract_numbers <- function(string){ 
  str_extract(string, "\\-*\\d+\\.*\\d*")
} 

collisions_subset_10000_renamed <- collisions_subset_10000 %>%
rename("Row original" = X,
       "Division of Records" = DR.Number,
       "Date Reported" = Date.Reported,
       "Date Occurred" = Date.Occurred,
       "Time Occurred" = Time.Occurred,
       "Area ID" = Area.ID,
       "Area Name" = Area.Name,
       "Reporting District" = Reporting.District,
       "Crime Code" = Crime.Code,
       "Crime Code Description" = Crime.Code.Description,
       "Modus Operandi Codes" = MO.Codes,
       "Victim Age" = Victim.Age,
       "Victim Sex" = Victim.Sex,
       "Victim Descent" = Victim.Descent,
       "Premise Code" = Premise.Code,
       "Premise Description" = Premise.Description,
       "Cross Street" = Cross.Street,
       "Zip Codes" = Zip.Codes,
       "Census Tracts" = Census.Tracts,
       "Precinct Boundaries" = Precinct.Boundaries,
       "LA Specific Plans" = LA.Specific.Plans,
       "Council Districts" = Council.Districts,
       "Neighborhood Councils" = Neighborhood.Councils..Certified.)%>%
  mutate(`Date Reported` = parse_date(str_sub(`Date Reported`, 0, 10)),
         `Date Occurred` = parse_date(str_sub(`Date Occurred`, 0, 10)),
         `Date Reported` = as.Date(`Date Reported`),
         `Date Occurred` = as.Date(`Date Occurred`))%>%
  separate(Location, c("Longitude","Latitude"), sep =',' )%>%
  mutate(Longitude = as.numeric(extract_numbers(Longitude)),
         Latitude = as.numeric(extract_numbers(Latitude))) %>%
  mutate(Longitude = as.character(extract_numbers(Longitude)),
         Latitude = as.character(extract_numbers(Latitude)),
         Longitude = as.numeric(Longitude),
         Latitude = as.numeric(Latitude))


# typeof(collisions_subset_10000_renamed$`Date Reported`)
# str(collisions_subset_10000_renamed)
# View(collisions_subset_10000_renamed)
#importing weather data 
#LAweather1 <- read_csv("~/Mscs 264 S19/Submit/MSCS_PROJECT_2019/LAweather1.csv")

#Code of the weather and tidy weather 1 and 2
LAweather1 <- read_csv("LAweather1.csv")
#View(LAweather1)
LAweather_US1CALA0030_1  <- LAweather1 %>%
  filter( STATION == "US1CALA0030")
#View(LAweather_US1CALA0030_1)

LAweather1.1 <- LAweather1 %>%
  select(DATE, PRCP)
#View(LAweather1.1)
LAweather1.1 <- LAweather_US1CALA0030_1 %>%
  select(DATE, PRCP) %>%
  mutate(date = as.Date(DATE))%>%
  rename("Date Occurred" = date)

#View(LAweather1.1)


#Renaming the dataset of the weather1.1 in order to make easier the merge with the collision dataset

final_weather_collision_1.1 <- merge(x = LAweather1.1,
                                 y= collisions_subset_10000_renamed, 
                                 by = "Date Occurred", all = TRUE)
#view(final_weather_collision_1.1)


#Reading weather 2 and mergin to final_weather_collision by PRCP
#LAweather2 <- read_csv("~/Mscs 264 S19/Submit/MSCS_PROJECT_2019/LAweather2.csv")
LAweather2 <- read_csv("LAweather2.csv")

LAweather_US1CALA0030_2  <- LAweather2 %>%
  filter( STATION == "US1CALA0030")
View(LAweather_US1CALA0030_2)
  

LAweather2.1 <- LAweather_US1CALA0030_2 %>%
  select(PRCP)
view(LAweather2.1)

LA_Collision_weather_complete <- merge(x = final_weather_collision_1.1, 
                                       y = LAweather2.1,
                                       by = "PRCP", all = TRUE)
#view(LA_Collision_weather_complete)


LA_Collision_complete_tidy<-LA_Collision_weather_complete[c(1,2,4:28)] 


View(LA_Collision_complete_tidy)




  

#typeof(collisions_subset_10000_renamed$Longitude)

#str(collisions_subset_10000_renamed)
#str(collisions_subset_10000_renamed)
#view(collisions_subset_10000_renamed)
#write.csv(collisions_subset, "Collision 5000.csv")
#write.csv(collisions_subset_10000_renamed, "tidy_collisions.csv")

```

```{r}
LA_map <- get_map(location = "los angeles, california", zoom = 12)
ggmap(LA_map)
```

```{r}
#heatmap 

#morning crashes 
mapset1 <- collisions_subset_10000_renamed %>%
  select(`Crime Code Description`, Longitude, Latitude, `Time Occurred`) %>% 
  filter(`Crime Code Description` == 'TRAFFIC COLLISION') %>%
  filter(`Time Occurred` < 900) %>%
  na.omit()


#evening crashes 
mapset2 <- collisions_subset_10000_renamed %>%
  select(`Crime Code Description`, Longitude, Latitude, `Time Occurred`) %>% 
  filter(`Crime Code Description` == 'TRAFFIC COLLISION') %>%
  filter(`Time Occurred` > 1800) %>%
  na.omit()

#midday crashes 
mapset3 <- collisions_subset_10000_renamed %>%
  select(`Crime Code Description`, Longitude, Latitude, `Time Occurred`) %>% 
  filter(`Crime Code Description` == 'TRAFFIC COLLISION') %>%
  filter(`Time Occurred` < 1500) %>%
  filter(`Time Occurred` > 900) %>%
  na.omit()

#ggmap(LA_map) + geom_density_2d()


morningmap <- ggmap(LA_map) + geom_density_2d(aes(x = Longitude, y = Latitude), data = mapset1) +
  stat_density2d(data = mapset1, 
    aes(x = Longitude, y = Latitude, fill = ..level.., alpha = ..level..), size = 0.01, 
    bins = 16, geom = "polygon") + scale_fill_gradient(low = "green", high = "red", 
    guide = FALSE) + scale_alpha(range = c(0, 0.3), guide = FALSE)


eveningmap <- ggmap(LA_map) + geom_density_2d(aes(x = Longitude, y = Latitude), data = mapset2) +
  stat_density2d(data = mapset2, 
    aes(x = Longitude, y = Latitude, fill = ..level.., alpha = ..level..), size = 0.01, 
    bins = 16, geom = "polygon") + scale_fill_gradient(low = "green", high = "red", 
    guide = FALSE) + scale_alpha(range = c(0, 0.3), guide = FALSE)


middaymap <- ggmap(LA_map) + geom_density_2d(aes(x = Longitude, y = Latitude), data = mapset3) +
  stat_density2d(data = mapset3, 
    aes(x = Longitude, y = Latitude, fill = ..level.., alpha = ..level..), size = 0.01, 
    bins = 16, geom = "polygon") + scale_fill_gradient(low = "green", high = "red", 
    guide = FALSE) + scale_alpha(range = c(0, 0.3), guide = FALSE)

```

```{r}
LA_map <- get_map(location = "los angeles, california", zoom = 12)
ggmap(LA_map)

#shiny app - interactive graph with buttons and sliders up top 
  
#heatmap and stuff below 
```

```{r}
#importing weather data 
LAweather1 <- read_csv("~/Mscs 264 S19/Submit/MSCS_PROJECT_2019/LAweather1.csv")
View(LAweather1)
LAweather1 %>% 
  filter(STATION == "US1CALA0036")

LAweather2 <- read_csv("~/Mscs 264 S19/Submit/MSCS_PROJECT_2019/LAweather2.csv")
#View(LAweather2)


```




